export const subjects = [
    {
        id: 'science',
        name: 'علوم',
        englishName: 'Science',
        icon: '🔬',
        worldName: 'Science World',
        color: 'green',
        image: '/assets/home/chemistry.png',
    },
    {
        id: 'arabic',
        name: 'عربي',
        englishName: 'Arabic',
        icon: '📚',
        worldName: 'Arabic World',
        color: 'rose',
        image: '/assets/home/arabic.png',
    },
    {
        id: 'english',
        name: 'إنجليزي',
        englishName: 'English',
        icon: '🔤',
        worldName: 'English World',
        color: 'blue',
        image: '/assets/home/english.png',
    },
    {
        id: 'math',
        name: 'حساب',
        englishName: 'Math',
        icon: '➗',
        worldName: 'Math World',
        color: 'amber',
        image: '/assets/home/math.png',
    },
];

export const grades = Array.from({ length: 9 }, (_, index) => ({
    id: `grade-${index + 1}`,
    level: index + 1,
    name: `الصف ${index + 1}`,
    label: `Grade ${index + 1}`,
}));

export const blockTypes = [
    { id: 'theory', name: 'شرح', helper: 'فقرة شرح أو تعريف مبسط.' },
    { id: 'example', name: 'مثال', helper: 'مثال محلول خطوة بخطوة.' },
    { id: 'worksheet', name: 'ورقة عمل', helper: 'سؤال تدريب مع خيارات.' },
    { id: 'quiz', name: 'اختبار قصير', helper: 'سؤال من اختبار متتابع.' },
    { id: 'game', name: 'لعبة', helper: 'نشاط لعب بسيط داخل الدرس.' },
    { id: 'news', name: 'خبر قصير', helper: 'معلومة ممتعة أو قصة قصيرة.' },
];

function lesson({
    id,
    title,
    thumbnail,
    intro,
    cards,
    examples,
    worksheet,
    quiz,
    visualTitle,
    visualItems,
}) {
    return {
        id,
        title,
        thumbnail,
        stars: 0,
        sections: {
            theory: {
                title: 'الشرح',
                intro,
                cards,
                visual: {
                    kind: 'custom',
                    title: visualTitle,
                    items: visualItems,
                },
            },
            examples,
            worksheet,
            quiz,
        },
    };
}

export const starterUnits = [
    {
        id: 'science-g1-u1',
        gradeId: 'grade-1',
        subjectId: 'science',
        level: 1,
        title: 'الحواس الخمس',
        subtitle: 'نتعرف على العالم من حولنا',
        locked: false,
        x: 17,
        y: 56,
        theme: 'nature',
        lessons: [
            lesson({
                id: 'science-g1-u1-l1',
                title: 'مقدمة الحواس',
                thumbnail: '👀',
                intro: 'الحواس الخمس تساعدنا على الفهم والتعلم بطريقة ممتعة كل يوم.',
                visualTitle: 'أدوات الحواس',
                visualItems: ['عين', 'أذن', 'أنف', 'لسان', 'يد'],
                cards: [
                    { badge: 'رؤية', title: 'العين', body: 'نستخدم العين لرؤية الألوان والأشكال.' },
                    { badge: 'سمع', title: 'الأذن', body: 'نستخدم الأذن لسماع الأصوات والموسيقى.' },
                    { badge: 'شم', title: 'الأنف', body: 'نستخدم الأنف لمعرفة الروائح.' },
                    { badge: 'تذوق', title: 'اللسان', body: 'نستخدم اللسان للتذوق.' },
                    { badge: 'لمس', title: 'اليد', body: 'نستخدم اليد لمعرفة الملمس.' },
                ],
                examples: [
                    {
                        title: 'مثال: سماع الجرس',
                        level: 'سهل',
                        prompt: 'عندما نسمع جرس المدرسة، أي حاسة نستخدم؟',
                        steps: ['نحدد نوع المثير: صوت.', 'الصوت نستقبله بالأذن.', 'إذن الحاسة هي السمع.'],
                        answer: 'الحاسة المستخدمة هي السمع.',
                    },
                    {
                        title: 'مثال: لون التفاحة',
                        level: 'سهل',
                        prompt: 'كيف نعرف أن التفاحة حمراء؟',
                        steps: ['ننظر للتفاحة.', 'العين ترى اللون.', 'إذن الحاسة هي الرؤية.'],
                        answer: 'الحاسة المستخدمة هي الرؤية.',
                    },
                ],
                worksheet: [
                    {
                        question: 'بماذا نرى الصور؟',
                        options: ['العين', 'الأذن', 'الأنف'],
                        answer: 'العين',
                        hint: 'الرؤية مرتبطة بالعين.',
                    },
                    {
                        question: 'بماذا نسمع الموسيقى؟',
                        options: ['الأذن', 'اليد', 'اللسان'],
                        answer: 'الأذن',
                        hint: 'الصوت يدخل عبر الأذن.',
                    },
                    {
                        question: 'أي عضو نستعمله للشم؟',
                        options: ['الأنف', 'العين', 'الفم'],
                        answer: 'الأنف',
                        hint: 'الشم مرتبط بالأنف.',
                    },
                ],
                quiz: [
                    { question: 'الحاسة المسؤولة عن الرؤية هي:', options: ['العين', 'اللسان', 'الأنف'], answer: 'العين', visual: '👀' },
                    { question: 'الحاسة المسؤولة عن السمع هي:', options: ['الأذن', 'اليد', 'العين'], answer: 'الأذن', visual: '👂' },
                    { question: 'الأنف يساعدنا على:', options: ['الشم', 'اللمس', 'السماع'], answer: 'الشم', visual: '👃' },
                    { question: 'اللسان يساعدنا على:', options: ['التذوق', 'الرؤية', 'الشم'], answer: 'التذوق', visual: '👅' },
                    { question: 'أي حاسة نستعمل لمعرفة أن الكوب بارد؟', options: ['اللمس', 'السمع', 'الرؤية'], answer: 'اللمس', visual: '✋' },
                ],
            }),
            lesson({
                id: 'science-g1-u1-l2',
                title: 'نشاط الحواس',
                thumbnail: '🎯',
                intro: 'في هذا النشاط نربط كل عضو بالحاسة الصحيحة بطريقة لعب.',
                visualTitle: 'تحدي المطابقة',
                visualItems: ['عين = رؤية', 'أذن = سمع', 'أنف = شم'],
                cards: [
                    { badge: 'لعبة', title: 'مطابقة سريعة', body: 'صل كل عضو بالحاسة المناسبة.' },
                    { badge: 'هدف', title: 'جمع النجوم', body: 'كل إجابة صحيحة تعطيك نجمة.' },
                ],
                examples: [
                    {
                        title: 'مثال: مطابقة',
                        level: 'تدريب',
                        prompt: 'إذا ظهر رمز الأذن ماذا تختار؟',
                        steps: ['ننظر للرمز.', 'نحدد العضو: أذن.', 'نختار: السمع.'],
                        answer: 'الاختيار الصحيح هو السمع.',
                    },
                ],
                worksheet: [
                    {
                        question: 'العين ↔ ؟',
                        options: ['الرؤية', 'الشم', 'اللمس'],
                        answer: 'الرؤية',
                        hint: 'العين للرؤية.',
                    },
                    {
                        question: 'اللسان ↔ ؟',
                        options: ['التذوق', 'السمع', 'الرؤية'],
                        answer: 'التذوق',
                        hint: 'اللسان للتذوق.',
                    },
                ],
                quiz: [
                    { question: 'الأذن تقابل:', options: ['السمع', 'الشم', 'اللمس'], answer: 'السمع', visual: '👂' },
                    { question: 'اليد تقابل:', options: ['اللمس', 'الرؤية', 'التذوق'], answer: 'اللمس', visual: '✋' },
                    { question: 'الأنف يقابل:', options: ['الشم', 'السمع', 'الرؤية'], answer: 'الشم', visual: '👃' },
                ],
            }),
        ],
    },
    {
        id: 'science-g1-u2',
        gradeId: 'grade-1',
        subjectId: 'science',
        level: 2,
        title: 'النباتات الصغيرة',
        subtitle: 'كيف تنمو النباتات؟',
        locked: false,
        x: 33,
        y: 44,
        theme: 'forest',
        lessons: [
            lesson({
                id: 'science-g1-u2-l1',
                title: 'أجزاء النبات',
                thumbnail: '🌱',
                intro: 'النبات يتكون من أجزاء تعمل معًا لتساعده على النمو.',
                visualTitle: 'مكونات النبات',
                visualItems: ['جذور', 'ساق', 'أوراق', 'زهرة'],
                cards: [
                    { badge: 'أساس', title: 'الجذور', body: 'تمتص الماء من التربة.' },
                    { badge: 'أساس', title: 'الساق', body: 'ينقل الماء والغذاء داخل النبات.' },
                    { badge: 'أساس', title: 'الأوراق', body: 'تصنع الغذاء باستخدام ضوء الشمس.' },
                ],
                examples: [
                    {
                        title: 'مثال: نبات عطشان',
                        level: 'سهل',
                        prompt: 'أي جزء يشرب الماء من التربة؟',
                        steps: ['الماء موجود في التربة.', 'الجذور داخل التربة.', 'إذن الجذور تمتص الماء.'],
                        answer: 'الجزء الصحيح هو الجذور.',
                    },
                ],
                worksheet: [
                    {
                        question: 'أي جزء يمتص الماء؟',
                        options: ['الجذور', 'الأوراق', 'الزهرة'],
                        answer: 'الجذور',
                        hint: 'الجذور توجد تحت الأرض.',
                    },
                    {
                        question: 'أي جزء يصنع الغذاء؟',
                        options: ['الأوراق', 'الساق', 'الجذور'],
                        answer: 'الأوراق',
                        hint: 'الأوراق تحتاج ضوء الشمس.',
                    },
                ],
                quiz: [
                    { question: 'الساق وظيفة:', options: ['نقل الماء', 'الشم', 'السماع'], answer: 'نقل الماء', visual: '🪴' },
                    { question: 'النبات يحتاج إلى:', options: ['ماء وضوء', 'رمل فقط', 'ظلام دائم'], answer: 'ماء وضوء', visual: '☀️' },
                    { question: 'الجزء الذي تحت التربة هو:', options: ['الجذور', 'الأوراق', 'الزهرة'], answer: 'الجذور', visual: '🌱' },
                ],
            }),
        ],
    },
    {
        id: 'science-g1-u3',
        gradeId: 'grade-1',
        subjectId: 'science',
        level: 3,
        title: 'الطقس والفصول',
        subtitle: 'صيف، شتاء، ربيع، خريف',
        locked: false,
        x: 48,
        y: 60,
        theme: 'weather',
        lessons: [
            lesson({
                id: 'science-g1-u3-l1',
                title: 'الفصول الأربعة',
                thumbnail: '🌦️',
                intro: 'يتغير الطقس خلال السنة حسب الفصل.',
                visualTitle: 'الفصول',
                visualItems: ['صيف', 'شتاء', 'ربيع', 'خريف'],
                cards: [
                    { badge: 'معلومة', title: 'الصيف', body: 'حار ومشمس في أغلب الأيام.' },
                    { badge: 'معلومة', title: 'الشتاء', body: 'بارد وقد يهطل المطر.' },
                ],
                examples: [
                    {
                        title: 'مثال: الملابس',
                        level: 'سهل',
                        prompt: 'ماذا نلبس في الشتاء؟',
                        steps: ['الشتاء بارد.', 'نحتاج ملابس ثقيلة.', 'نلبس معطفًا دافئًا.'],
                        answer: 'ملابس ثقيلة ودافئة.',
                    },
                ],
                worksheet: [
                    {
                        question: 'الفصل الحار غالبًا هو:',
                        options: ['الصيف', 'الشتاء', 'الخريف'],
                        answer: 'الصيف',
                        hint: 'الشمس تكون أقوى في الصيف.',
                    },
                    {
                        question: 'الفصل البارد غالبًا هو:',
                        options: ['الشتاء', 'الربيع', 'الصيف'],
                        answer: 'الشتاء',
                        hint: 'نحتاج ملابس دافئة في الشتاء.',
                    },
                ],
                quiz: [
                    { question: 'المطر يكثر غالبًا في:', options: ['الشتاء', 'الصيف', 'الربيع'], answer: 'الشتاء', visual: '🌧️' },
                    { question: 'الفصل المناسب للسباحة غالبًا:', options: ['الصيف', 'الخريف', 'الشتاء'], answer: 'الصيف', visual: '🏖️' },
                ],
            }),
        ],
    },
    {
        id: 'arabic-g1-u1',
        gradeId: 'grade-1',
        subjectId: 'arabic',
        level: 1,
        title: 'حروف اللغة العربية',
        subtitle: 'نتعلم الحروف وأصواتها',
        locked: false,
        x: 19,
        y: 58,
        theme: 'letters',
        lessons: [
            lesson({
                id: 'arabic-g1-u1-l1',
                title: 'حرف الألف',
                thumbnail: 'أ',
                intro: 'نتعرف على شكل حرف الألف وصوته في بداية الكلمة.',
                visualTitle: 'كلمات بحرف الألف',
                visualItems: ['أسد', 'أرنب', 'أم'],
                cards: [
                    { badge: 'حرف', title: 'شكل الحرف', body: 'الألف حرف مستقيم ويكتب هكذا: أ' },
                    { badge: 'صوت', title: 'نطق الحرف', body: 'صوت الألف واضح في أول الكلمة.' },
                ],
                examples: [
                    {
                        title: 'مثال: أَسَد',
                        level: 'سهل',
                        prompt: 'ما الحرف الأول في كلمة أسد؟',
                        steps: ['نقرأ الكلمة.', 'نحدد الحرف الأول.', 'الحرف هو الألف.'],
                        answer: 'الحرف الأول هو الألف.',
                    },
                ],
                worksheet: [
                    {
                        question: 'اختر الكلمة التي تبدأ بحرف الألف:',
                        options: ['أسد', 'بيت', 'قلم'],
                        answer: 'أسد',
                        hint: 'الألف في بداية كلمة أسد.',
                    },
                ],
                quiz: [
                    { question: 'حرف الألف شكله:', options: ['أ', 'ب', 'ت'], answer: 'أ', visual: 'أ' },
                    { question: 'أي كلمة تبدأ بالألف؟', options: ['أم', 'باب', 'قمر'], answer: 'أم', visual: '📖' },
                ],
            }),
        ],
    },
    {
        id: 'english-g1-u1',
        gradeId: 'grade-1',
        subjectId: 'english',
        level: 1,
        title: 'English Alphabet',
        subtitle: 'Letters A to F',
        locked: false,
        x: 20,
        y: 56,
        theme: 'alphabet',
        lessons: [
            lesson({
                id: 'english-g1-u1-l1',
                title: 'Letter A',
                thumbnail: 'A',
                intro: 'We learn the shape and sound of letter A.',
                visualTitle: 'Words with A',
                visualItems: ['Apple', 'Ant', 'Airplane'],
                cards: [
                    { badge: 'Letter', title: 'Uppercase & lowercase', body: 'A and a are the same letter in two forms.' },
                    { badge: 'Sound', title: 'A sound', body: 'The short sound appears in words like apple.' },
                ],
                examples: [
                    {
                        title: 'Example: Apple',
                        level: 'Easy',
                        prompt: 'Which letter starts the word apple?',
                        steps: ['Read the word.', 'Check the first letter.', 'It starts with A.'],
                        answer: 'The word starts with A.',
                    },
                ],
                worksheet: [
                    {
                        question: 'Choose the word that starts with A:',
                        options: ['Apple', 'Ball', 'Cat'],
                        answer: 'Apple',
                        hint: 'Apple starts with A.',
                    },
                ],
                quiz: [
                    { question: 'Uppercase of a is:', options: ['A', 'B', 'C'], answer: 'A', visual: 'A' },
                    { question: 'Which letter do you hear in apple?', options: ['A', 'M', 'S'], answer: 'A', visual: '🍎' },
                ],
            }),
        ],
    },
    {
        id: 'math-g1-u1',
        gradeId: 'grade-1',
        subjectId: 'math',
        level: 1,
        title: 'الأعداد من 1 إلى 10',
        subtitle: 'العد والتمييز',
        locked: false,
        x: 18,
        y: 55,
        theme: 'numbers',
        lessons: [
            lesson({
                id: 'math-g1-u1-l1',
                title: 'العد التصاعدي',
                thumbnail: '1',
                intro: 'نتعلم عد الأرقام بالترتيب من 1 إلى 10.',
                visualTitle: 'سلم الأرقام',
                visualItems: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
                cards: [
                    { badge: 'مفهوم', title: 'الترتيب', body: 'نعد بترتيب صحيح دون قفز أرقام.' },
                    { badge: 'تدريب', title: 'الربط', body: 'نربط الرقم بعدد الأشياء.' },
                ],
                examples: [
                    {
                        title: 'مثال: عد التفاحات',
                        level: 'سهل',
                        prompt: 'إذا لدينا 3 تفاحات، ما الرقم المناسب؟',
                        steps: ['نعد التفاحات.', 'عددها ثلاثة.', 'الرقم المناسب هو 3.'],
                        answer: 'الرقم الصحيح هو 3.',
                    },
                ],
                worksheet: [
                    {
                        question: 'ما الرقم بعد 4؟',
                        options: ['5', '3', '6'],
                        answer: '5',
                        hint: 'عد بالتسلسل: 1،2،3،4،5.',
                    },
                    {
                        question: 'ما الرقم قبل 9؟',
                        options: ['8', '7', '10'],
                        answer: '8',
                        hint: 'الرقم السابق لـ9 هو 8.',
                    },
                ],
                quiz: [
                    { question: 'الرقم بعد 6 هو:', options: ['7', '5', '8'], answer: '7', visual: '7' },
                    { question: 'كم عدد أصابع اليد الواحدة؟', options: ['5', '4', '6'], answer: '5', visual: '✋' },
                    { question: 'الرقم قبل 2 هو:', options: ['1', '3', '0'], answer: '1', visual: '1' },
                ],
            }),
        ],
    },
    {
        id: 'math-g7-u1',
        gradeId: 'grade-7',
        subjectId: 'math',
        level: 1,
        title: 'الحوادث وأنواعها',
        subtitle: 'بسيط، مركب، مؤكد، مستحيل',
        locked: false,
        x: 17,
        y: 58,
        theme: 'probability',
        lessons: [
            lesson({
                id: 'math-g7-u1-l1',
                title: 'فضاء العينة والحادث',
                thumbnail: '🎲',
                intro: 'في الاحتمالات نبدأ بتحديد كل النتائج الممكنة ثم نختار الحدث المطلوب.',
                visualTitle: 'رمي حجر النرد',
                visualItems: ['1', '2', '3', '4', '5', '6'],
                cards: [
                    { badge: 'أساس', title: 'فضاء العينة', body: 'كل النتائج الممكنة للتجربة.' },
                    { badge: 'أساس', title: 'الحادث', body: 'مجموعة جزئية من فضاء العينة.' },
                    { badge: 'تصنيف', title: 'أنواع الحوادث', body: 'بسيط، مركب، مؤكد، مستحيل.' },
                ],
                examples: [
                    {
                        title: 'مثال: حدث بسيط',
                        level: 'سهل',
                        prompt: 'ظهور الرقم 5 عند رمي نرد.',
                        steps: ['نحدد النتيجة المطلوبة.', 'يوجد عنصر واحد فقط.', 'إذن الحادث بسيط.'],
                        answer: 'الحدث البسيط يحتوي عنصرًا واحدًا.',
                    },
                    {
                        title: 'مثال: حدث مركب',
                        level: 'متوسط',
                        prompt: 'ظهور عدد زوجي عند رمي نرد.',
                        steps: ['الأعداد الزوجية هي 2 و4 و6.', 'عدد العناصر أكبر من واحد.', 'إذن الحادث مركب.'],
                        answer: 'الحدث المركب يحتوي أكثر من عنصر.',
                    },
                ],
                worksheet: [
                    {
                        question: 'فضاء العينة عند رمي نرد مرة واحدة هو:',
                        options: ['{1,2,3,4,5,6}', '{1,2,3}', '{2,4,6}'],
                        answer: '{1,2,3,4,5,6}',
                        hint: 'كل النتائج من 1 إلى 6.',
                    },
                    {
                        question: 'الحدث {3} يعتبر:',
                        options: ['بسيط', 'مركب', 'مؤكد'],
                        answer: 'بسيط',
                        hint: 'لأنه يحتوي عنصرًا واحدًا.',
                    },
                    {
                        question: 'الحدث {2,4,6} يعتبر:',
                        options: ['مركب', 'بسيط', 'مستحيل'],
                        answer: 'مركب',
                        hint: 'لأنه يحتوي أكثر من عنصر.',
                    },
                ],
                quiz: [
                    { question: 'الحدث المستحيل يكون:', options: ['فارغ {}', 'يساوي فضاء العينة', 'عنصر واحد'], answer: 'فارغ {}', visual: '∅' },
                    { question: 'الحدث المؤكد يكون:', options: ['يساوي فضاء العينة', 'فارغ', 'عنصرين فقط'], answer: 'يساوي فضاء العينة', visual: 'Ω' },
                    { question: 'الحدث {4} هو:', options: ['بسيط', 'مركب', 'مستحيل'], answer: 'بسيط', visual: '4' },
                    { question: 'الأعداد الزوجية على النرد:', options: ['2,4,6', '1,3,5', '1,2,3'], answer: '2,4,6', visual: '🎲' },
                    { question: 'عدد عناصر فضاء العينة للنرد هو:', options: ['6', '3', '12'], answer: '6', visual: '6' },
                ],
            }),
        ],
    },
];
